In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt


In [3]:
df = pd.read_csv("winequality-white.csv",sep=";")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [19]:
df['quality'].unique()

array([6, 5, 7, 8, 4, 3, 9])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1:]

In [13]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  
0         8.8  
1         9.5  
2        10.1  
3         9.9  
4         9.9  
...       ...  
4893     11.2  
4894      9.6  
4895      9.4  
4896     12.8  
4897     11.8  

[4898 rows x 11 columns]

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
X_train.shape

(3918, 11)

In [18]:
from tensorflow.keras import models,layers

In [ ]:
from tensorflow

In [20]:
model = models.Sequential([
    layers.Dense(50,input_shape=(11,),activation='relu',),
    layers.Dense(50,activation='relu'),
    layers.Dense(10,activation='sigmoid')
])

C:\Users\Sanjana Shankar\tf_env\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [21]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])  #BinaryCrossentropy;#categorical_crossentropy

In [22]:
model.fit(X_train,y_train,epochs=5)

Epoch 1/5
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1773 - loss: 6.9185
Epoch 2/5
123/123 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2496 - loss: 1.4176
Epoch 3/5
123/123 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2693 - loss: 1.3363
Epoch 4/5
123/123 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2831 - loss: 1.3401
Epoch 5/5
123/123 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3035 - loss: 1.2773


In [25]:
from sklearn.neural_network import MLPClassifier

In [26]:
ypred = model.predict(X_test)

31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step


In [27]:
ypred

array([[2.2504516e-06, 2.1835019e-22, 9.4746977e-01, ..., 1.0000000e+00,
        9.9999994e-01, 9.9998987e-01],
       [5.5814476e-06, 4.7611063e-19, 8.3993018e-01, ..., 9.9999988e-01,
        9.9999875e-01, 9.9947631e-01],
       [6.3270463e-06, 3.4181446e-18, 7.8554702e-01, ..., 9.9999976e-01,
        9.9999738e-01, 9.9917954e-01],
       ...,
       [1.4806612e-06, 5.2052617e-22, 9.6501660e-01, ..., 1.0000000e+00,
        9.9999982e-01, 9.9999404e-01],
       [1.2427051e-06, 1.9976731e-21, 9.1164267e-01, ..., 9.9999994e-01,
        9.9999845e-01, 9.9997693e-01],
       [4.0878606e-07, 1.0956374e-21, 8.2006365e-01, ..., 9.9999994e-01,
        9.9999946e-01, 9.9989128e-01]], dtype=float32)

In [1]:
yp = np.argmax(ypred,axis=1)

NameError: name 'np' is not defined

In [29]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,roc_curve

In [30]:
print(accuracy_score(y_test,yp))

0.35


In [31]:
print(confusion_matrix(y_test,yp))

[[  2   1   2   0   0   0]
 [  2   3  14   6   0   0]
 [ 20  56 107 104   4   0]
 [ 18  47 130 229   8   0]
 [  3  11  48 128   2   0]
 [  0   1   5  28   1   0]]


In [32]:
print(classification_report(y_test,yp))

              precision    recall  f1-score   support

           3       0.04      0.40      0.08         5
           4       0.03      0.12      0.04        25
           5       0.35      0.37      0.36       291
           6       0.46      0.53      0.49       432
           7       0.13      0.01      0.02       192
           8       0.00      0.00      0.00        35

    accuracy                           0.35       980
   macro avg       0.17      0.24      0.17       980
weighted avg       0.33      0.35      0.33       980



C:\Users\Sanjana Shankar\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sanjana Shankar\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sanjana Shankar\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [33]:
mlp = MLPClassifier(
    activation='relu',
    solver='adam'
)

In [34]:
mlp.fit(X_train,y_train)

C:\Users\Sanjana Shankar\tf_env\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1124: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier()

In [35]:
p = mlp.predict(X_test)

In [36]:
p

array([6, 7, 6, 6, 6, 6, 5, 4, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 5, 6, 7, 6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 7, 6, 6, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 6, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6,
       6, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6,
       5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 7, 5, 6, 7, 7,
       6, 6, 6, 5, 7, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5,
       6, 6, 6, 4, 4, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5,
       6, 6, 5, 6, 6, 6, 5, 6, 6, 7, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5,

In [37]:
print(confusion_matrix(y_test,p))

[[  1   0   1   3   0   0]
 [  1   2   8  14   0   0]
 [  0   3  66 221   1   0]
 [  0   0  25 396  11   0]
 [  0   0   1 178  13   0]
 [  0   0   1  28   6   0]]


In [38]:
print(accuracy_score(y_test,p))

0.48775510204081635


In [40]:
print(classification_report(y_test,p))

              precision    recall  f1-score   support

           3       0.50      0.20      0.29         5
           4       0.40      0.08      0.13        25
           5       0.65      0.23      0.34       291
           6       0.47      0.92      0.62       432
           7       0.42      0.07      0.12       192
           8       0.00      0.00      0.00        35

    accuracy                           0.49       980
   macro avg       0.41      0.25      0.25       980
weighted avg       0.49      0.49      0.40       980



C:\Users\Sanjana Shankar\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sanjana Shankar\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sanjana Shankar\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [41]:
data = pd.read_csv("CarPrice_Assignment.csv")
data.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [42]:
X = data.iloc[:,-5:-1]
y = data.iloc[:,-1:]

In [43]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [44]:
X_train.shape

(164, 4)

In [45]:
model = models.Sequential([
    layers.Dense(100,input_shape=(4,),activation='relu'),
    layers.Dense(10,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

C:\Users\Sanjana Shankar\tf_env\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [47]:
model.compile(optimizer='adam',loss='mse',metrics=['mae'])

In [48]:
model.fit(X_train,y_train,epochs=10)

Epoch 1/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 246322592.0000 - mae: 13486.3477
Epoch 2/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 245225840.0000 - mae: 13447.5332
Epoch 3/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 218923632.0000 - mae: 12824.0312
Epoch 4/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 255794016.0000 - mae: 13889.0000 
Epoch 5/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 239392720.0000 - mae: 13195.5684
Epoch 6/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 220719824.0000 - mae: 12980.3115 
Epoch 7/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 231987776.0000 - mae: 13279.8018 
Epoch 8/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 216279904.0000 - mae: 12712.8008
Epoch 9/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 245501376.0000 - mae: 13471.2314
Epoch 10/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 262154896.0000 - mae: 13874.1699


In [49]:
pred = model.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step


In [50]:
from sklearn.metrics import r2_score

In [51]:
print(r2_score(y_test,pred))

-2.3048009872436523


In [52]:
from sklearn.neural_network import MLPRegressor

In [53]:
m=MLPRegressor(activation='relu',solver='adam')

In [55]:
m.fit(X_train,y_train)

C:\Users\Sanjana Shankar\tf_env\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1650: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Sanjana Shankar\tf_env\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor()

In [57]:
ypred=m.predict(X_test)

In [58]:
r2_score(y_test,ypred)

-0.07187607408613284